import { LAB_ID } from '../api/curriculum';
import type { LabMaterial } from '../api/curriculum';
import LabTools from '../components/LabTools';
import ChatBar from '../components/ChatBar';
import StatusLine from '../components/StatusLine';

interface Props {
  lab: LabMaterial | null;
  busy: boolean;
  error: string | null;
  onApprove: () => Promise<boolean>;
  onRequestChanges: (feedback: string) => Promise<boolean>;
}

export default function LabQuizPreview({ lab, busy, error, onApprove, onRequestChanges }: Props) {
  return (
    <div className="content-card">
      <div className="content-header">
        <div className="content-title">
          <h2>{lab ? `${lab.title} — Quiz` : 'Lab Quiz'}</h2>
          <p>
            {lab
              ? `${LAB_ID} · ${lab.quiz.length} questions · Generated by AI · v${lab.version} · ${lab.approval_status.replace('_', ' ')}`
              : 'Generate the lab on the Lab Tasks tab first'}
          </p>
        </div>
        <div className="content-actions">
          {/* The agent generates spec, quiz and rubric together; an optional quiz is a Phase 2 change. */}
          <button className="btn-outline" disabled title="The quiz is generated together with the lab tasks">
            Generate Quiz
          </button>
          <div className="content-actions-divider" />
          <button
            className="btn-approve"
            disabled={!lab || busy || lab.approval_status === 'approved'}
            onClick={() => void onApprove()}
          >
            {lab?.approval_status === 'approved' ? 'Approved' : 'Approve'}
          </button>
        </div>
      </div>

      <hr className="content-divider" />
      <StatusLine busy={busy} error={error} />
      <LabTools lab={lab} pdfs={[{ kind: 'quiz', label: 'Quiz' }]} />

      {lab?.quiz.map(q => (
        <div key={q.id} className="question-item">
          {q.id.toUpperCase()}.  {q.question}
          <div className="question-meta">{q.type.replace('_', ' ')} · {q.rubric_points} pts · {q.difficulty}</div>
        </div>
      ))}

      <ChatBar
        placeholder='Ask the agent to refine the quiz...  e.g. "Make Q3 harder" or "Add a question about traversal"'
        disabled={!lab || busy}
        onSend={onRequestChanges}
      />
    </div>
  );
}
