import { useState } from 'react';

const questions = [
  'Q1.  What is the time complexity of inserting a node at the head of a singly linked list?',
  'Q2.  Explain the difference between a singly and doubly linked list.',
  'Q3.  Write pseudocode for deleting a node with a given value.',
  'Q4.  What happens when you lose the reference to the head node?',
  'Q5.  How would you detect a cycle in a linked list? Describe the algorithm.',
];

export default function MaterialPreview() {
  const [prompt, setPrompt] = useState('');

  return (
    <div className="content-card">
      <div className="content-header">
        <div className="content-title">
          <h2>Lab 4 — Linked Lists Tasks</h2>
          <p>5 tasks · Generated by AI · Pending approval</p>
        </div>
        <div className="content-actions">
          <button className="btn-outline">Generate Lab Tasks</button>
          <div className="content-actions-divider" />
          <button className="btn-approve">Approve</button>
        </div>
      </div>

      <hr className="content-divider" />

      {questions.map((q, i) => (
        <div key={i} className="question-item">{q}</div>
      ))}

      <div className="prompt-input-bar">
        <input
          type="text"
          placeholder='Ask the agent to refine this content...  e.g. "Make Q3 harder" or "Add a question about traversal"'
          value={prompt}
          onChange={e => setPrompt(e.target.value)}
        />
        <button className="btn-send">Send</button>
      </div>
    </div>
  );
}
