import { useState } from 'react';
import { LAB_ID } from '../api/curriculum';
import type { LabMaterial } from '../api/curriculum';
import LabTools from '../components/LabTools';
import ChatBar from '../components/ChatBar';
import StatusLine from '../components/StatusLine';

interface Props {
  lab: LabMaterial | null;
  busy: boolean;
  error: string | null;
  onGenerate: (title: string, learningObjectives: string[]) => Promise<boolean>;
  onApprove: () => Promise<boolean>;
}

export default function MaterialPreview({ lab, busy, error, onGenerate, onApprove }: Props) {
  const [title, setTitle] = useState('');
  const [objectives, setObjectives] = useState('');

  const objectiveList = objectives.split('\n').map(o => o.trim()).filter(Boolean);
  const canGenerate = !busy && (lab !== null || (title.trim() !== '' && objectiveList.length > 0));

  function generate() {
    // With an existing lab, regenerate from its own title and objectives.
    void (lab ? onGenerate(lab.title, lab.learning_objectives) : onGenerate(title.trim(), objectiveList));
  }

  return (
    <div className="content-card">
      <div className="content-header">
        <div className="content-title">
          <h2>{lab ? `${lab.title} — Tasks` : 'Lab Tasks'}</h2>
          <p>
            {lab
              ? `${LAB_ID} · Generated by AI · v${lab.version} · ${lab.approval_status.replace('_', ' ')}`
              : 'No lab generated yet'}
          </p>
        </div>
        <div className="content-actions">
          <button className="btn-outline" disabled={!canGenerate} onClick={generate}>Generate Lab Tasks</button>
          <div className="content-actions-divider" />
          <button
            className="btn-approve"
            disabled={!lab || busy || lab.approval_status === 'approved'}
            onClick={() => void onApprove()}
          >
            {lab?.approval_status === 'approved' ? 'Approved' : 'Approve'}
          </button>
        </div>
      </div>

      <hr className="content-divider" />
      <StatusLine busy={busy} error={error} />
      <LabTools lab={lab} pdfs={[{ kind: 'lab', label: 'Lab' }, { kind: 'rubric', label: 'Rubric' }]} />

      {lab ? (
        <pre className="spec-text">{lab.spec_markdown}</pre>
      ) : (
        <div className="lab-form">
          <label className="form-label" htmlFor="lab-title">Lab title</label>
          <input
            id="lab-title"
            className="form-input"
            type="text"
            placeholder="e.g. Linked Lists"
            value={title}
            onChange={e => setTitle(e.target.value)}
          />
          <label className="form-label" htmlFor="lab-objectives">Learning objectives (one per line)</label>
          <textarea
            id="lab-objectives"
            className="modal-textarea"
            rows={5}
            placeholder={'Implement a singly linked list\nAnalyze insertion complexity'}
            value={objectives}
            onChange={e => setObjectives(e.target.value)}
          />
        </div>
      )}

      <ChatBar
        placeholder="Refinement chat is on the Lab Quiz tab: requested changes regenerate the quiz and rubric."
        disabled
        onSend={async () => false}
      />
    </div>
  );
}
